### primeira funcionalidade
GET http://localhost:5164

### Listar Produtos
GET http://localhost:5164/produto/listar

### Cadastrar Produtos
POST http://localhost:5164/produto/cadastrar/memesBrasileiros



# ### segundo teste - texto aleatória
# GET http://localhost:5164/mickey

# ### terceiro teste - um dynamic dentro do GetMap()
# GET http://localhost:5164/retornarEndereco

# ### quarto teste - receber info pela URL da requesição
# GET http://localhost:5164/receberinfo/Pedro/19

# ### quito teste - receber info pelo corpo
# GET http://localhost:5164/receberinfopelocorpo
# Content-Type: application/json

# {
#   "Nome": "Pedro",
#   "Idade": 19
# }

# ### sexto teste
# GET http://localhost:5164/lista